version: '3.8'

services:
  mindspark-app:
    build: .
    container_name: mindspark-app
    ports:
      - "8501:8501"
    environment:
      - MINDSPARK_ENV=production
      - REDIS_URI=redis://redis:6379
      - CHAT_STORE_KEY=docker_user
      - HF_ENDPOINT=https://hf-mirror.com
      # 从.env文件加载环境变量
      - env_file=.env.docker
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./localmodels:/app/localmodels
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      vector-store:
        condition: service_healthy
    networks:
      - mindspark-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: mindspark-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mindspark-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  vector-store:
    image: chromadb/chroma:latest
    container_name: mindspark-vector-store
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - mindspark-network
    restart: unless-stopped
    environment:
      - ALLOW_RESET=TRUE
      - ANONYMIZED_TELEMETRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    container_name: mindspark-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - mindspark-network
    restart: unless-stopped
    # 可选：预加载常用模型
    # environment:
    #   - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: mindspark-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mindspark-app
    networks:
      - mindspark-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  chroma_data:
  ollama_data:

networks:
  mindspark-network:
    driver: bridge
